### ISSUE TITLE
The new support for default text for Repeater Field broke the old qTranslate Text Field in Repeater

### ISSUE THREAD

**Issue by Gasimzada** [funkjedi/acf-qtranslate#28]
It made repeater completely useless because everything would get destroyed inside it. Also, can you please add support for disabling translation for the default ACF text field?

**Comment by alancwoo** [comment]
I'm writing here as I noticed the same problem, ACF qtranslate causes my repeater fields and relationship fields to flush all their contents when saved.

I initially reported this bug to qtranslate-x thinking the problem was on their end, (and also to ACF), but realized that disabling ACF qtranslate allows these fields to save properly again.

I've described it in detail on the [qtranslate-x tracker](https://github.com/qTranslate-Team/qtranslate-x/issues/119) and also on the [ACF forum](http://support.advancedcustomfields.com/forums/topic/warning-repeater-fields-flushed-after-upgrading-to-latest-qtranslate-x-3-2-9/).

**Confirmed** Rolling back to 1.7.5 fixes the problem

**Comment by Gasimzada** [comment]
If you change the repeater field types to default text (not qTranslate Text), the problem is solved. The problem exists because JavaScript doesn't update the hidden qtranslate field and an empty hidden field with name being an array overwrites previous values of the array and in this case the array is empty, so the form data is empty (was this proper English?). This really causes a major headache for me because there were some text fields that doesn't need to get translated and he big in the qtranslate not working in repeaters was very helpful. I would have wished to disable default texts being translated but now no input fields would translate because qTranslate Text doesn't work...


> I'm writing here as I noticed the same problem, ACF qtranslate causes my repeater fields and relationship fields to flush all their contents when saved.
> 
> I initially reported this bug to qtranslate-x thinking the problem was on their end, (and also to ACF), but realized that disabling ACF qtranslate allows these fields to save properly again.
> 
> I've described it in detail on the qtranslate-x tracker and also on the ACF forum.
> 
> Confirmed Rolling back to 1.7.5 fixes the problem
>

**Comment by Tyratox** [comment]
For me it actually didn't solve the problem to just change the type of the fields. No field inside the repeater field gets saved while this plugin is activated. I hope this gets fixed soon.

**Comment by fburatti** [comment]
Clearing the browser cache and cookies, all back to work perfectly, at least for me (confirmed here https://github.com/funkjedi/acf-qtranslate/issues/22#issuecomment-89731550)

**Comment by fburatti** [comment]
Unfortunately I have to correct my comment, the problem is still present with version 1.7.6, so I had to go back to version 1.7.5. I'm not using the repeater but flexible content, however it seems the same.

**Comment by cnasikas** [comment]
For those you have a problem with 1.7.5 on the repeater field with text, editor etc I notice that if I fill first the fields that are not being translated ie images etc , save/update the post and then go fill the other fields like text, editor etc that are being translated and then save again it accept it. It's weird.

In 1.7.6 the problem still present.

**Comment by Gasimzada** [comment]
@cnasikas for repeater fields in 1.7.5, using qTranslate Text instead of default Text works without any new problems.

**Comment by cnasikas** [comment]
Thanks for the update, didn't notice it.

**Comment by funkjedi** [comment]
The latest release addresses these issues.

**Comment by Tusko** [comment]
Using 
ACF 5.2.2
ACF qTranslate 1.7.6
qTranslate-X 3.3


Repeater doesn't work! Help me! Live project doesn't works 3 days!!!

**Comment by loganyott** [comment]
Also still experiencing issues.
ACF 5.2.5
acf-qtranslate 1.7.9
qtranslate-x 3.4.2

**Comment by loganyott** [comment]
I created a new Field Group with
- Repeater
-- Text
-- Text

First time I added it to a page,  values would flush when I saved. Tried this a few times. For a different page, I created a new Field Group with
- Repeater
-- Flexible Content
---- Repeater
------ Text
------ Text

Interestingly, this second version including the Flexible Content worked. I should also note that *existing* Field Groups with the first structure updated properly. Very mysterious behavior.
